name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: pypi
      url: https://pypi.org/p/larakit

    steps:
      - name: Checkout LaraKit
        uses: actions/checkout@v4

      - name: Setup Python environment
        run: pip3 install -r requirements.txt

      - name: Build Python package
        run: python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

    permissions:
      id-token: write